#!/bin/sh

if [ X$1 = "Xclean" ];then
  rm -rf *_cache/
  rm -rf *_files/
fi

rm -f *.html *.pdf


buildVignette(){
  Rscript -e "rmarkdown::render('$1')"
}

buildVignette coop.Rmd
buildVignette algos.Rmd

cp *.Rmd ../inst/doc/
cp *.html ../inst/doc/
